TRANSCRIPT_CSV_DIR = "./demo_data/"
STREAMING_JSON_FILENAME = "streaming_data.json"
EXTRACRTED_KEYWORDS_JSON_FILENAME = "extracted_keywords.json"
SPEAKER_GROUP_KEYWORDS_JSON_FILENAME = "grouped_extracted_keywords.json"

# KEYWORD_EXTRACTION_MAIN_CONTEXT = f"""
#         Task:
#         - Extract keywords from the given text input.

#         Output Format:
#                 - Return a JSON object with a top-level key "keywords".
#                 - "keywords" must be a list of strings representing the extracted keywords.
#         - Example:
#                 {{
#                         "keywords": [keyword1, keyword2, ...]      
#                 }}

#         Instructions:
#         - each sentence is formed as speaker: text.
#         - the keywords should be extracted from the text input, and should not be generated by the model itself.
#         - the keywords should not be speaker names, but should be related to the content of the text.
#         - sentences can belong to multiple keywords if they are semantically related to multiple keywords.
#         - keywords should have different meanings, and should not be too similar to each other.
#         """
KEYWORD_EXTRACTION_MAIN_CONTEXT = """
You are a topic labeler for meeting and debate transcripts.
Your job is to identify the key discussion topics from a speaker's utterance,
for display as short bubble labels on a visualization screen.
You are to highly prioritize reusing previously created keywords, as long as it makes sense.

Input format: "SpeakerName: utterance text"

Instructions:
- Prioritize reusing previously identified keywords, as long as it makes sense.
- Extract 0 to a maximum of 5 topic keywords or phrases that capture the main subjects discussed.
- Each keyword must be 1 to a maximum of 4 words long.
- Keywords should be meaningful topic labels that clearly describe the concept being discussed.
  They do not have to be exact words from the text — use cleaner terminology if it better captures the topic.
  Example: prefer "pre-existing conditions" over "the thing about people who had cancer before".
- Do NOT extract speaker names, greetings, filler phrases, or procedural statements
  (e.g., "thank you", "let's get going", "I agree").
- If the utterance contains no meaningful topic content, return an empty list.
- All keywords in the list must be distinct — no near-duplicates or overlapping topics.
"""
MODEL="gpt-5-mini-2025-08-07"