TRANSCRIPT_CSV_FILENAME = "./demo_data/formatted_1.csv"
STREAMING_JSON_FILENAME = "streaming_data.json"
EXTRACRTED_KEYWORDS_JSON_FILENAME = "extracted_keywords.json"
SPEAKER_GROUP_KEYWORDS_JSON_FILENAME = "grouped_extracted_keywords.json"

KEYWORD_EXTRACTION_MAIN_CONTEXT = f"""
        Task:
        - Extract keywords from the given text input.

        Output Format:
                - Return a JSON object with a top-level key "keywords".
                - "keywords" must be a list of strings representing the extracted keywords.
        - Example:
                {{
                        "keywords": [keyword1, keyword2, ...]      
                }}

        Instructions:
        - each sentence is formed as speaker: text.
        - the keywords should be extracted from the text input, and should not be generated by the model itself.
        - the keywords should not be speaker names, but should be related to the content of the text.
        - no keyword for a sentence is also acceptable if the sentence does not contain any meaningful information.
        - the keywords should be concise and informative, often a single noun or noun phrase.
        - sentences can belong to multiple keywords if they are semantically related to multiple keywords.
        - keywords should have different meanings, and should not be too similar to each other.
        """

MODEL="gpt-5-mini-2025-08-07"