TRANSCRIPT_CSV_DIR = "./demo_data/"
STREAMING_JSON_FILENAME = "streaming_data.json"
EXTRACRTED_KEYWORDS_JSON_FILENAME = "extracted_keywords.json"
SPEAKER_GROUP_KEYWORDS_JSON_FILENAME = "grouped_extracted_keywords.json"

KEYWORD_EXTRACTION_MAIN_CONTEXT = f"""
        Task:
        - Extract keywords from the given text input.

        Output Format:
                - Return a JSON object with a top-level key "keywords".
                - "keywords" must be a list of strings representing the extracted keywords.
        - Example:
                {{
                        "keywords": [keyword1, keyword2, ...]      
                }}

        Instructions:
        - each sentence is formed as speaker: text.
        - the keywords should be extracted from the text input, and should not be generated by the model itself.
        - the keywords should not be speaker names, but should be related to the content of the text.
        - sentences can belong to multiple keywords if they are semantically related to multiple keywords.
        - keywords should have different meanings, and should not be too similar to each other.
        """

MODEL="gpt-5-mini-2025-08-07"

KEYWORD_CONSOLIDATION_CONTEXT = """
You are a keyword deduplicator for meeting transcripts.

You will receive a list of topic keywords extracted from a meeting.
Your job is to group synonyms and near-duplicates together under one canonical label.

Instructions:
- Max 2 words per keyword, the purpose of this is to provide a very high level overview.
- Return a JSON object with a single key "mapping".
- "mapping" is a list of objects, each with "original" and "canonical" fields.
- Every input keyword must appear as an "original" entry.
- Keywords that need no merging map to themselves (original == canonical).
- Choose the clearest, most concise label as the canonical form.
- Merge keywords that refer to the same concept (e.g. "COVID-19", "coronavirus", "the pandemic" → "COVID-19").
- Do NOT merge keywords that are genuinely distinct topics.

Example output:
{
  "mapping": [
    {"original": "COVID-19", "canonical": "COVID-19"},
    {"original": "coronavirus", "canonical": "COVID-19"},
    {"original": "the pandemic", "canonical": "COVID-19"},
    {"original": "healthcare", "canonical": "healthcare"},
    {"original": "health care", "canonical": "healthcare"}
  ]
}
"""