TRANSCRIPT_JSON_FILENAME = "one_episode.json"
OVERALL_EXTRACRTED_KEYWORDS_JSON_FILENAME = "overall_extracted_keywords.json"
OVERALL_GROUPED_EXTRACTED_KEYWORDS_JSON_FILENAME = "overall_grouped_extracted_keywords.json"

KEYWORD_EXTRACTION_MAIN_CONTEXT = f"""
        Task:
        - Extract keywords from the given text input.

        Output Format:
                - Return a JSON object with a top-level key "results".
                - "results" must be a list of dictionaries that each contain:
                  - "keyword": string
                  - "items": list of transcript lines related to that keyword
        - Example:
                {{
                        "results": [
                                {{
                                        "keyword": "keyword1",
                                        "items": ["sentence1", "sentence2", "sentence3"]
                                }},
                                {{
                                        "keyword": "keyword2",
                                        "items": ["sentence4", "sentence5", "sentence6"]
                                }}
                        ]
                }}
        Instructions:
        - each sentence is formed as [timestamp] speaker: text, breaking by a new line.
        - not all sentences need to be included in the output, only those that are semantically related to the keyword.
        - sentence must not be modified when included in the output, and should be included as is.
        - the keywords should be extracted from the text input, and should not be generated by the model itself.
        - sentences can belong to multiple keywords if they are semantically related to multiple keywords.
        - keywords should have different meanings, and should not be too similar to each other.
        """

MODEL="gpt-5-mini-2025-08-07"